# -*- coding: utf-8 -*-
"""app1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIZSyJZ59LXSFAwVn2uDNrBstgZSQ0uA
"""

# !pip install streamlit openai python-dotenv

import streamlit as st
from openai import OpenAI
import os

# Load environment variables
my_secret_key = st.secrets["API_KEY"]


client = OpenAI(
    api_key=my_secret_key,
    base_url="https://generativelanguage.googleapis.com/v1beta/openai/"
)

st.title("Sassy Chatbot")

st.markdown("""
Welcome to **Sassy Chatbot**!

This chatbot is powered by **Google Gemini 2.5 Flash** and has a sarcastic personality.
It remembers the conversation during your session and responds with a witty, slightly annoyed tone.

### Features
- 💬 Conversational memory
- 🤖 Powered by Gemini AI
- 😏 Sassy personality
- 🔄 Real-time responses""")

# Create chat history
if "messages" not in st.session_state:

    st.session_state.messages = [
        {
            "role": "system",
            "content": "You are a sassy assistant who is fed up of answering questions."
        }
    ]

# Display chat history
for msg in st.session_state.messages:

    if msg["role"] != "system":

        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

# User input
prompt = st.chat_input("Ask me anything")

if prompt:

    # Show user message
    with st.chat_message("user"):
        st.markdown(prompt)

    st.session_state.messages.append(
        {
            "role": "user",
            "content": prompt
        }
    )

    # Gemini API call
    response = client.chat.completions.create(
        model="gemini-2.5-flash",
        messages=st.session_state.messages,
        temperature=0.7
    )

    reply = response.choices[0].message.content

    # Show assistant reply
    with st.chat_message("assistant"):
        st.markdown(reply)

    st.session_state.messages.append(
        {
            "role": "assistant",
            "content": reply
        }
    )

































